myapp/apps/employee/urls.py
from django.conf.urls import url

from . import views
from models import Employee

app_name = 'employee'
urlpatterns = [
    url(r'employee_list/$', views.IndexView.as_view(paginate_by=10), name="employee_list"),
    url(r'create_employee/$', views.create_employee, name="create_employee"),
    url(r'filter_records/$', views.filter_records, name="filter_records"),
    url(r'search_records/$', views.search_records, name="search_records"),
    url(r'ajax-test/$', views.ajax_test, name="ajax_test"),
	url(r'edit/(?P<id>\w+)/$', views.edit_employee, name="edit_employee_details"),
#	url(r'employee/(?P<employee_id>\w+)/$', views.detail, name="detail"),
    url(r'profile/$', views.profile, name="my_portfolio"),
    url(r'my/cv/$', views.download_cv, name="my_cv"),
]

myapp/myapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.employee.urls')),
    url(r'^lists', include('apps.lists.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/templates/home/experience.html
<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h2>Projects</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 animate-box fadeInLeft" data-animate-effect="fadeInLeft">
					<div class="testimony">
						<h4>Investment Banking Tool</h4>
						<blockquote>
						Development of a framework to automate the process of getting data from various financial sources and using it as high value solutions for investment banks and asset management firms. Today, a vast majority of strategy and investment analyses is being done manually and consequently based on limited data sets leading to slow and sub optimal business decisions. We developed a realtime data monitoring as well as giving them value additions such as exporting whole interface to required Powerpoint presentations by click of a button.
						</blockquote>
						<p class="author"><cite>Boston Analytics</cite></p>
					</div>
				</div>
				<div class="col-md-4 animate-box">
					<div class="testimony">
						<h4>Bluejacks Tracker</h4>
						<blockquote>
							Bluejacks Tracker is a web based application to maintain records of the project for a client, and keep track of the progress been made on it. It also has an interface for the employee’s working on the project, playing different roles in the project, they submit the records for their tasks being completed and the Tracker gets updated. Looking to the Tracker at once a Project Manager can come to know about the progress been made so far in the project. The system sends email, with all the information about the next step to be taken, to all the concerned persons. It also contains a reporting module, which creates a csv on a button click.
						</blockquote>
						<p class="author"><cite>Six Red Marbles Learning Pvt Ltd.</cite></p>
					</div>
				</div>
				<div class="col-md-4 animate-box">
					<div class="testimony">
						<h4>Pre Joining Portal</h4>
						<blockquote>
							Pre joining portal was developed to help the HR of the firm as he can easily collect all the necessary information from the new joinee before the joining of a new candidate. He can use his information which is generally required to perform some of the necessary formalities which saves a employee's crucial time on the day of his joining. 
						</blockquote>
						<p class="author"><cite>LaxmiKumaran & Sridharan</cite></p>
					</div>
				</div>
			</div>
		</div>

myapp/templates/home/header.html
<div class="overlay"></div>
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1 text-center">
			<div class="display-t">
				<div class="display-tc animate-box" data-animate-effect="fadeIn">
					<h1>Prateek Chaurasia</h1>
					<h2>Enthusiast Web Developer</h2>
				</div>
			</div>
		</div>
	</div>
</div>

myapp/templates/home/menu.html
<div class="container">
	<div class="row">
		<div class="col-xs-2">
			<div id="fh5co-logo">
				<a href="{% url 'employee:my_cv' %}" title="Download Updated CV">PC</a>
			</div>
		</div>
		<div class="col-xs-10 text-right menu-1">
			<ul>
				<li class="active"><a href="index.html">Home</a></li>
				<li><a href="#skills">Skills</a></li>
				<li><a href="#fh5co-testimonial">Projects</a></li>
				<!--<li class="has-dropdown">
					<a href="#">Tools</a>
					<ul class="dropdown">
						<li><a href="#">HTML5</a></li>
						<li><a href="#">CSS3</a></li>
						<li><a href="#">Sass</a></li>
						<li><a href="#">jQuery</a></li>
					</ul>
				</li>
				<li><a href="contact.html">Contact</a></li>-->
			</ul>
		</div>
	</div>
</div>

myapp/templates/home/skills.html
<div class="container">
	<div class="row">
		<div id="fh5co-features-2">
			<div class="col-feature-9">
				<div class="row">
					<div class="col-md-12 fh5co-heading animate-box">
						<h2>Core Competencies</h2>
						<p>A full-stack developer, having experience in the listed technologies.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-7 col-sm-7 col-md-pull-2 col-sm-pull-2 animate-box" data-animate-effect="fadeInRight">
						<div class="feature-image">
							<img src="images/work_1.png" alt="work">
						</div>
					</div>
					<div class="col-md-5 col-sm-5">
						<div class="feature-left animate-box" data-animate-effect="fadeInLeft">
							<span class="icon">
								<i class="icon-check"></i>
							</span>
							<div class="feature-copy">
								<h3>Languages</h3>
								<p>Python, JavaScript, HTML, CSS, AJAX</p>
							</div>
						</div>

						<div class="feature-left animate-box" data-animate-effect="fadeInLeft">
							<span class="icon">
								<i class="icon-check"></i>
							</span>
							<div class="feature-copy">
								<h3>Frameworks</h3>
								<p>Django, Bootstrap</p>
							</div>
						</div>

						<div class="feature-left animate-box" data-animate-effect="fadeInLeft">
							<span class="icon">
								<i class="icon-check"></i>
							</span>
							<div class="feature-copy">
								<h3>Operating System</h3>
								<p>Linux(Ubuntu), Windows(7 and Above), Mac OSX</p>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-feature-3">
				<div id="fh5co-counter" class="fh5co-bg fh5co-counter">
					<div class="row">
						<div class="col-md-12 fh5co-heading animate-box">
							<p>Usage of technologies in terms of percentage.</p>
						</div>
					</div>
					<div class="row">
						<div class="display-t">
							<div class="display-tc">
								<div class="col-md-12 animate-box">
									<div class="feature-center">
										<span class="counter js-counter" data-from="0" data-to="80" data-speed="5000" data-refresh-interval="50">1</span>
										<span class="counter-label">Python</span>

									</div>
								</div>
								<div class="col-md-12 animate-box">
									<div class="feature-center">
										<span class="counter js-counter" data-from="0" data-to="80" data-speed="5000" data-refresh-interval="50">1</span>
										<span class="counter-label">Django</span>
									</div>
								</div>
								<div class="col-md-12 animate-box">
									<div class="feature-center">
										<span class="counter js-counter" data-from="0" data-to="75" data-speed="5000" data-refresh-interval="50">1</span>
										<span class="counter-label">JavaScript</span>
									</div>
								</div>
								<div class="col-md-12 animate-box">
									<div class="feature-center">
										<span class="counter js-counter" data-from="0" data-to="75" data-speed="5000" data-refresh-interval="50">1</span>
										<span class="counter-label">HTML & CSS</span>

									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>