myapp/apps/employee/urls.py
from django.conf.urls import url

from . import views
from models import Employee

app_name = 'employee'
urlpatterns = [
    url(r'employee_list/$', views.IndexView.as_view(paginate_by=10), name="employee_list"),
    url(r'create_employee/$', views.create_employee, name="create_employee"),
    url(r'filter_records/$', views.filter_records, name="filter_records"),
    url(r'search_records/$', views.search_records, name="search_records"),
    url(r'ajax-test/$', views.ajax_test, name="ajax_test"),
	url(r'edit/(?P<id>\w+)/$', views.edit_employee, name="edit_employee_details"),
#	url(r'employee/(?P<employee_id>\w+)/$', views.detail, name="detail"),
    url(r'profile/$', views.profile, name="my_portfolio"),
    url(r'my/cv/$', views.download_cv, name="my_cv"),
]

myapp/myapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.employee.urls')),
    url(r'^lists', include('apps.lists.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/apps/employee/models.py
from django.db import models
from datetime import datetime

class Employee(models.Model):
	name = models.CharField(verbose_name='Name', max_length=50)
	email = models.EmailField()
	phone = models.CharField(verbose_name='Phone Number', default='', max_length=200)
	designation = models.CharField(max_length=200, verbose_name='Designation')
	dob = models.DateField()
	is_active = models.BooleanField(default=1)
	created_date = models.DateTimeField(auto_now=True, editable=False)
	modified_date = models.DateTimeField(auto_now=True, editable=False)

	def __unicode__(self):
		return u'%s -- %s'%(self.name, self.email)

myapp/apps/employee/forms.py
from django import forms
from models import Employee
from myapp import settings
from django.utils.translation import ugettext_lazy as _

class EmployeeForm(forms.ModelForm):
	dob = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
	class Meta:
		model = Employee
		exclude = ['is_active','created_date','modified_date']
		help_texts = {
            'dob': _('Please enter date in dd-mm-yyyy or yyyy-mm-dd formats'),
        }

myapp/apps/employee/views.py
import mimetypes
import os
import urllib2, urllib
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from models import Employee
from rest_data import retail_data
from forms import EmployeeForm
from django.views import generic
from django.shortcuts import get_object_or_404
from django.utils.encoding import smart_str

PROJECT_PATH = os.path.realpath(os.path.dirname(__file__))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



def ajax_test(request):
#	import ipdb;ipdb.set_trace()
	if request.method == 'GET':
		retail_list = retail_data
		print request.session.get('match_one', "Not Exists")
		print request.session.get('match_all', "Not Exists")
		return JsonResponse(retail_data)

def detail(request, employee_id):
	movie = get_object_or_404(Employee, pk=employee_id)
	return render(request, 'detail.html', {'movie': movie})


def filter_records(request):
	context = {}
	if request.method == 'POST':
		match_query = request.POST.get('match_query')
		context['match_query'] = match_query
	return render(request, 'filter_form.html',context)
		

def search_records(request):
	context = {}
	if request.method == 'POST':
		match_query_one = request.POST.get('check_one', "")
		match_query_all = request.POST.get('check_all', "")
		if match_query_one:
			val1 = request.POST.get('test1', "")
			val2 = request.POST.get('test2', "")
			val3 = request.POST.get('test3', "")
			val4 = request.POST.get('test4', "")
			request.session['match_one'] = {"values": [
				val1, val2, val3, val4
			]}
			return redirect('employee:ajax_test')
		else:
			val1 = request.POST.get('check1', "")
			val2 = request.POST.get('check2', "")
			val3 = request.POST.get('check3', "")
			val4 = request.POST.get('check4', "")
			request.session['match_all'] = {"values": [
				val1, val2, val3, val4
			]}
			return redirect('employee:ajax_test')
		

class IndexView(generic.ListView):
	template_name = 'user_list.html'
	context_object_name = 'employee_list'
	
	def get_queryset(self):
		"""Returns the list of employee filtered by recently created profile"""
		return Employee.objects.all().order_by('-created_date')


def create_employee(request):
	context = {}
	if request.method == 'POST':
		data = request.POST.get('form_data').split('&')
		data_dict = {}
		for d in data:
			data_dict[d.split("=")[0]] = urllib.unquote_plus(d.split("=")[1])
		form = EmployeeForm(data=data_dict)
		if form.is_valid():
			print "Data being sucessfully saved"
			form.save()
			return JsonResponse({'status': 'success'})
		else:
			error_dict = form.errors
			message = "Entered data is incorrect"
			return JsonResponse({'status': 'fail',
							'err_dict': error_dict, 
							'err_message': message})
	else:
		form = EmployeeForm()
		context['form'] = form
		context['err_dict'] = {}
	return render(request, 'employee_form.html',context)


def edit_employee(request, id):
	emp_id = id
	data = Employee.objects.get(id=emp_id)
	context = {}
	if request.method == 'POST':
		updated_data = request.POST.get('form_data').split('&')
		data_dict = {}
		for d in updated_data:
			data_dict[d.split("=")[0]] = urllib.unquote_plus(d.split("=")[1])
		print "Data coming in from form: ",data_dict
		form = EmployeeForm(data_dict, instance=data)
		if form.is_valid():
			print "Data being sucessfully updated"
			form.save()
			return JsonResponse({'status': 'success'})
		else:
			error_dict = form.errors
			message = "Entered data is incorrect"
			return JsonResponse({'status': 'fail',
							'err_dict': error_dict, 
							'err_message': message})
	else:
		form = EmployeeForm(instance=data)
		context['form'] = form
		context['id'] = emp_id
	return render(request, 'update_employee.html', context)

def profile(request):
	return render(request, 'portfolio.html', {})

def download_cv(request):
	file_path = os.path.join(BASE_DIR, 'static/docs/Prateek_Resume-8.doc')
	download_name = "Resume.doc"
	response = HttpResponse(content_type='application/force-download')
	response['Content-Length'] = os.path.getsize(file_path)
	response['Content-Disposition'] = "attachment; filename=%s"%smart_str(download_name)
	response['X-Sendfile'] = smart_str(file_path)
	return response

#def create_update_user(request, id=None):
#    '''This function will render a form to add a new user,
#    as well as to edit an existing user details.
#    '''
##     import ipdb;ipdb.set_trace()
#    context = RequestContext(request)
#    form_header = ''
#    if id and request.method == 'POST':
#        # This gets executed for a edit request.
#        instance = User.objects.get(id=id)
#        form = UserForm(request.POST, instance=instance)
#        if form.is_valid():
#            form.save()
#        else:
#            return render_to_response('user_form.html',
#                              {'form': form,
#                               'form_header': form_header,},
#                              context)
#        return HttpResponseRedirect(reverse("user_list"))
#    elif id:
#        user_id = id
#        user_obj = User.objects.get(id=user_id)
#        form = UserForm(instance=user_obj)
#        form_header = 'Edit User Details'
#    elif request.method == 'POST':
#        # This gets executed for a new user request.
#
#        form = UserForm(request.POST)
#        if form.is_valid():
#            form.save()
#        else:
#            return render_to_response('user_form.html',
#                              {'form': form,
#                               'form_header': form_header,},
#                              context)
#		return HttpResponseRedirect(reverse("user_list"))
#    else:
#        form = UserForm()
#        form_header = 'Add New User Details'
#    return render_to_response('user_form.html',
#                              {'form': form,
#                               'form_header': form_header},
#                              context)

myapp/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
    	<meta charset="UTF-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">	
    	<title>
	    	{% block title %}
	        {% endblock %}
        </title>	
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
<!--		<link rel="stylesheet" href="{% static 'css/base.css' %}"> -->
        {% block head %}
        {% endblock %}
    </head>
    <body>
    	<div id="header" class="container bg-primary" style="min-height: 150px;">
			<div class="row">
				<div class="col-md-5 col-md-offset-4 col-xs-12">
					<h2>Employee APP</h2>
				</div>
			</div>
	    	{% block header %}
	    	{% endblock %}
    	</div>
    	
    	<div style="clear:both"></div>
    	
    	<div id="container" class="container bg-info">
	    	{% block container %}
	    	{% endblock %}
    	</div>
    	<div style="clear:both"></div>
    	
    	<div id="footer" class="container" style="min-height:100px;">
			<div class="row">
				<div class="col-md-12 bg-primary col-xs-12">
					<p class="pull-right">copyright@sadhnaTech.com</p>
				</div>
			</div>
	    	{% block footer %}
	    	{% endblock %}
    	</div>
        
    </body>
</html>

myapp/templates/detail.html
{% extends "base.html" %}
{% block title %}Details Check{% endblock %}

{% block head %}
	<style>
		.fieldWrapper{
		width: 200px;
		}	
	</style>
{% endblock %}


{% block container %}
	<div id='main_div'>
	<ul class="list">
      {% for movie in movies %}
        <li>
			{{ movie.id }}
        </li>
      {% endfor %}
	</ul>
	</div>
{% endblock %}

myapp/templates/employee_form.html
{% extends "base.html" %}
{% block title %}Create New Employee{% endblock %}

{% block head %}
	<style>
		.fieldWrapper{
		width: 200px;
		}	
	</style>
	<script type="text/javascript">
	function create_emp(){
		var form = $('#employee_form');
		$.ajax({
			type: "POST",
			url: "/create_employee/",
			data: {'form_data': form.serialize(), csrfmiddlewaretoken: '{{ csrf_token }}',},
			success: function(data){
					if(data.status == 'success'){
						window.location.href = "/employee_list/"
						console.log('Employee Updated successfully');
					}else{
						$('#error').text(data.err_message);
						if(data.err_dict.hasOwnProperty('name')){
							$('#name_err').text(data.err_dict.name[0]);
						}	
						if(data.err_dict.hasOwnProperty('email')){
							$('#email_err').text(data.err_dict.email[0]);	
						}
						if(data.err_dict.hasOwnProperty('phone')){
							$('#phone_err').text(data.err_dict.phone[0]);	
						}
						if(data.err_dict.hasOwnProperty('dob')){
							$('#dob_err').text(data.err_dict.dob[0]);
						}	
						if(data.err_dict.hasOwnProperty('designation')){
							$('#designation_err').text(data.err_dict.designation[0]);	
						}
					}
					},
			error: function(err){
					console.log(err);
			}
		});
	}
	</script>
{% endblock %}


{% block container %}
	{% if err_message %}
		<span id="error">
		{{ err_message }}
		</span>
	{% endif %}
		<div class="row">
			<div class="col-md-8 col-md-offset-4 col-xs-12">
				<h2>
					Create New Employee
				</h2>
			</div>
			<form action="" method="POST" id="employee_form" class="form-horizontal">{% csrf_token %}
			{{ form.non_field_errors }}
				<div class="form-group">
					{{ err_dict.name }}
					<label for="{{ form.name.id_for_label }}" class="col-md-1 col-md-offset-4 col-xs-3">Name:</label>
					<div class="col-md-5 col-xs-9">
						{{ form.name }}
					<span id="name_err" class="text-danger"></span>
					</div>
				</div>
				<div class="form-group">
					{{ err_dict.email }}
					<label for="{{ form.email.id_for_label }}" class="col-md-1 col-md-offset-4 col-xs-3">Email:</label>
					<div class="col-md-5 col-xs-9">
						{{ form.email }}
					<span id="email_err" class="text-danger"></span>
					</div>
				</div>
				<div class="form-group">
					{{ err_dict.phone }}
					<label for="{{ form.phone.id_for_label }}" class="col-md-1 col-md-offset-4 col-xs-3">Phone Number:</label>
					<div class="col-md-5 col-xs-9">
						{{ form.phone }}
					<span id="phone_err" class="text-danger"></span>
					</div>
				</div>
				<div class="form-group">
					{{ err_dict.dob }}
					<label for="{{ form.dob.id_for_label }}" class="col-md-1 col-md-offset-4 col-xs-3">Date of Birth:</label>
					<div class="col-md-5 col-xs-9">
						{{ form.dob }}
					<span id="dob_err" class="text-danger"></span>
					</div>
				</div>	
				<div class="form-group">
					{{ err_dict.designation }}
					<label for="{{ form.designation.id_for_label }}" class="col-md-1 col-md-offset-4 col-xs-3">Designation:</label>
					<div class="col-md-5 col-xs-9">
						{{ form.designation }}
					<span id="designation_err" class="text-danger"></span>
					</div>
				</div>	
				<div class="form-group">
					<div class="col-md-7 col-md-offset-5 col-xs-7 col-xs-offset-5">
						<input type="button" value="SUBMIT" class="btn btn-primary btn-sm" onclick="create_emp();">
					</div> 
				</div>
			</form>
		</div>
		<div class="row">	
			<div class="col-md-6">
				<form method="POST" action="{% url 'employee:filter_records' %}">{% csrf_token %}
					<input type="hidden" name="match_query" value="match_one"/>
					<input type="submit" value="Filter 1"/>
				</form>
			</div>
			<div class="col-md-6">
				<form method="POST" action="{% url 'employee:filter_records' %}">{% csrf_token %}
					<input type="hidden" name="match_query" value="match_all"/>
					<input type="submit" value="Filter All"/>
				</form>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<table id="example" class="display" width="100%" cellspacing="0">
						<thead>
							<tr>
								<th>Name</th>
								<th>Position</th>
								<th>Office</th>
								<th>Extn.</th>
								<th>Start date</th>
								<th>Salary</th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>Name</th>
								<th>Position</th>
								<th>Office</th>
								<th>Extn.</th>
								<th>Start date</th>
								<th>Salary</th>
							</tr>
						</tfoot>
			</table>	
			</div>
		</div>
		<script type="text/javascript">
	        $(document).ready(function() {
	           $('#example').DataTable( {
				"processing": true,
	           "ajax": "/ajax-test/",
			   "type": "POST",
				"columnDefs": [ {
							"targets": -1,
							"data": null,
							"render": function ( data, type, row, meta ) {
							  				return '<a href="'+row[5].es_id+'">Download</a>';
											}
						  }]
	            });
	        });
	    </script>
{% endblock %}

myapp/templates/filter_form.html
{% extends "base.html" %}
{% block title %}Filter Records Form{% endblock %}

{% block head %}
	<style>
		.fieldWrapper{
		width: 200px;
		}	
	</style>
{% endblock %}


{% block container %}
	<div class="row">
		<div class="col-md-6 col-md-offset-4">
		{% if match_query == 'match_one' %}
			<form action={% url 'employee:search_records' %} method="POST">{% csrf_token %}
				<input type="hidden" name="test1" value="1"/>
				<input type="hidden" name="test2" value="2"/>
				<input type="hidden" name="test3" value="3"/>
				<input type="hidden" name="test4" value="4"/>
				<input type="radio" name="check_one" value="Yes"/>Yes</br>
				<input type="radio" name="check_one" value="No"/>No
				<input type="submit" value="Filter">
			</form>
		{% else %}
			<form action={% url 'employee:search_records' %} method="POST">{% csrf_token %}
				<input type="hidden" name="check1" value="A"/>
				<input type="hidden" name="check2" value="B"/>
				<input type="hidden" name="check3" value="C"/>
				<input type="hidden" name="check4" value="D"/>
				<input type="radio" name="check_all" value="Yes"/>Yes</br>
				<input type="radio" name="check_all" value="No"/>No
				<input type="submit" value="Filter">
			</form>
		{% endif %}
		</div>
	</div>
{% endblock %}

myapp/templates/portfolio.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
    	<meta charset="UTF-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">	
    	<title>
	    	{% block title %}
	        {% endblock %}
        </title>	
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/animate.css' %}">
		<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
		<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!--		<link rel="stylesheet" href="{% static 'css/base.css' %}"> -->
		<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
        {% block head %}
        {% endblock %}
    </head>
    <body>
		<div id="page">       
			<nav class="fh5co-nav" role="navigation">
				{% include "home/menu.html" %}
			</nav>
			<header id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url(images/img_bg_1.jpg);">
				{% include "home/header.html" %}
			</header>
			<div class="container" id="fh5co-testimonial">
				{% include "home/experience.html" %}
			</div>
			<div class="fh5co-bg-section" id="skills">
				{% include "home/skills.html" %}
			</div>			
		</div>

		<!--Including different scripts used in the page. --> 
		<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
		<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
		<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
		<script src="{% static 'js/jquery.countTo.js' %}"></script>
		<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
		<script src="{% static 'js/magnific-popup-options.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

myapp/templates/update_employee.html
{% extends "base.html" %}
{% block title %}Update Employee{% endblock %}

{% block head %}
	<style>
		.fieldWrapper{
		width: 200px;
		}	
	</style>
	<script type="text/javascript">
	function update_emp(){
		var form = $('#employee_form');
		$.ajax({
			type: "POST",
			url: "/edit/"+{{ id }}+"/",
			data: {'form_data': form.serialize(), csrfmiddlewaretoken: '{{ csrf_token }}',},
			success: function(data){
					if(data.status == 'success'){
						window.location.href = "/employee_list/"
						console.log('Employee Updated successfully');
					}else{
						$('#error').text(data.err_message);
						if(data.err_dict.hasOwnProperty('name')){
							$('#name_err').text(data.err_dict.name[0]);
						}	
						if(data.err_dict.hasOwnProperty('email')){
							$('#email_err').text(data.err_dict.email[0]);	
						}
						if(data.err_dict.hasOwnProperty('phone')){
							$('#phone_err').text(data.err_dict.phone[0]);	
						}
						if(data.err_dict.hasOwnProperty('dob')){
							$('#dob_err').text(data.err_dict.dob[0]);
						}	
						if(data.err_dict.hasOwnProperty('designation')){
							$('#designation_err').text(data.err_dict.designation[0]);	
						}
					}
					},
			error: function(err){
					console.log(err);
			}
		});
	}
	</script>
{% endblock %}

{% block container %}
	{% if err_message %}
		<span id="error">
		{{ err_message }}
		</span>
	{% endif %}
		<div class="row">
			<div class="col-md-8 col-md-offset-4">
				<h2>Update Employee Details</h2>
			</div>
					
			<form action="" method="POST" id="employee_form" class="form-horizontal">{% csrf_token %}
			{{ form.non_field_errors }}
				<div class="form-group">
					{{ err_dict.name }}
					<label for="{{ form.name.id_for_label }}" class="col-md-1 col-md-offset-4">Name:</label>
					<div class="col-md-5">
						{{ form.name }}
					<span id="name_err" class="text-danger"></span>
					</div>
				</div>
				<div class="form-group">
					{{ err_dict.email }}
					<label for="{{ form.email.id_for_label }}" class="col-md-1 col-md-offset-4">Email:</label>
					<div class="col-md-5">
						{{ form.email }}
					<span id="email_err" class="text-danger"></span>
					</div>
				</div>
				<div class="form-group">
					{{ err_dict.phone }}
					<label for="{{ form.phone.id_for_label }}" class="col-md-1 col-md-offset-4">Phone Number:</label>
					<div class="col-md-5">
						{{ form.phone }}
					<span id="phone_err" class="text-danger"></span>
					</div>
				</div>
				<div class="form-group">
					{{ err_dict.dob }}
					<label for="{{ form.dob.id_for_label }}" class="col-md-1 col-md-offset-4">Date of Birth:</label>
					<div class="col-md-5">
						{{ form.dob }}
					<span id="dob_err" class="text-danger"></span>
					</div>
				</div>	
				<div class="form-group">
					{{ err_dict.designation }}
					<label for="{{ form.designation.id_for_label }}" class="col-md-1 col-md-offset-4">Designation:</label>
					<div class="col-md-5">
						{{ form.designation }}
					<span id="designation_err" class="text-danger"></span>
					</div>
				</div>	
				<div class="form-group">
					<div class="col-md-7 col-md-offset-5">
						<input type="button" value="UPDATE" class="btn btn-primary btn-sm" onclick="update_emp();"">
					</div> 
				</div>
			</form>
		</div>
{% endblock %}






	

myapp/templates/user_list.html
{% extends "base.html" %}
{% block title %}Employee List{% endblock %}
{% load staticfiles %}

{% block head %}
	<script type="text/javascript">
		function editEmployee(event, id){
			event.preventDefault();
			$.ajax({
				type: "POST",
				url: '/edit/'+id,
				data: {'csrfmiddlewaretoken': '{{ csrf_token }}',},
				success: function(data){
					alert(data);
					console.log(data);
				},
				error: function(err){
					console.log(err);
				}
			});
		}		
	</script>
{% endblock %}


{% block container %}
	<div id='row'>
		<div col-md-12>
			<h2>Employee List</h2>
		</div>
		<div col-md-12>
			<a href="{% url 'employee:create_employee' %}" class="pull-right">
				<span class="glyphicon glyphicon-plus" aria-hidden="true">Create Employee</span>
			</a>
		</div>
		<div class="clearfix"></div>
		<div class="table-responsive">
			<table id="employee_lst" class="table table-striped table-bordered table-hover">
				<thead>
					<tr>
						<th>Name</th>
						<th>Email</th>
						<th>Phone</th>
						<th>Designation</th>
						<th>DOB</th>
						<th>Update Link</th>
						<!--<th>Employee ID Link</th>-->
					</tr>
				</thead>
				<tbody>
					{% for emp in employee_list %}
						<tr>
							<td>{{ emp.name }}</td>
							<td>{{ emp.email }}</td>
							<td>{{ emp.phone }}</td>
							<td>{{ emp.designation }}</td>
							<td>{{ emp.dob }}</td>
							<td><a href="{% url 'employee:edit_employee_details' id=emp.id %}">Update</a></td> 
							<!--<td><a href="#" onclick="editEmployee(event, {{emp.id}})">Update</a></td> -->
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}